language: node_js
node_js:
  - '10'

before_deploy:
  - yarn build

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: dist
    skip-cleanup: true
    on:
      branch: master
